# Generated by Django 6.0.7 on 2026-07-08 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoteAves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('tipo_ave', models.CharField(max_length=50)),
                ('cantidad_inicial', models.IntegerField()),
                ('cantidad_actual', models.IntegerField()),
                ('fecha_ingreso', models.DateField()),
                ('estado', models.CharField(default='Activo', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='AlimentacionAves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alimento', models.CharField(max_length=100)),
                ('cantidad_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avicola.loteaves')),
            ],
        ),
        migrations.CreateModel(
            name='Mortalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_bajas', models.IntegerField()),
                ('causa', models.TextField(blank=True, null=True)),
                ('fecha', models.DateField()),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avicola.loteaves')),
            ],
        ),
    ]
