# Generated by Django 6.0.7 on 2026-07-08 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('area_asignada', models.CharField(max_length=50)),
                ('fecha_siembra', models.DateField()),
                ('estado', models.CharField(default='En proceso', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cosecha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cosecha', models.DateField()),
                ('cantidad_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('calidad', models.CharField(max_length=50)),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hortalizas.cultivo')),
            ],
        ),
        migrations.CreateModel(
            name='FaseProceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_fase', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hortalizas.cultivo')),
            ],
        ),
    ]
